import 'package:pandora_flutter_mobile/tweet.dart';


var tweets = [
  Tweet(
    // avatar: 'https://pbs.twimg.com/profile_images/1187814172307800064/MhnwJbxw_400x400.jpg',
    avatar:'https://www.best4geeks.com/wp-content/uploads/2018/08/48-lovely-cute-girl-picture-1024x816.jpg',
    username: 'Flutter',
    name: 'FlutterDev',
    timeAgo: '5m',
    text: 'Google’s UI toolkit to build apps for mobile, web, & desktop from a single codebase.',
    comments: '243',
    retweets: '23K',
    favorites: '112K',
  ),
  Tweet(
    avatar: 'https://writestylesonline.com/wp-content/uploads/2016/08/Follow-These-Steps-for-a-Flawless-Professional-Profile-Picture.jpg',
    username: 'Flutter en Español',
    name: 'EsFlutter',
    timeAgo: '12m',
    text: 'Comunidad Flutter de habla hispana!',
    comments: '46',
    retweets: '4K',
    favorites: '17K',
  ),
  Tweet(
    avatar: 'https://th.bing.com/th/id/R.bc9993d6b4ffc40622dcea75acf6c6dd?rik=w01gHU3pXz79Cg&riu=http%3a%2f%2f3.bp.blogspot.com%2f-Tfz6G_zsZkc%2fUhhnZ4aGwkI%2fAAAAAAAAEtk%2fHplbqw1xr_Y%2fs1600%2fa%2b(17).jpg&ehk=obAySeuTCDrB49SvrzOhcc%2bXxfIAxWqCd%2fwt196xX8k%3d&risl=&pid=ImgRaw&r=0',
    username: 'Android Dev',
    name: 'AndroidDev',
    timeAgo: '20m',
    text: 'News and announcements for developers from the Android team.',
    comments: '305',
    retweets: '20K',
    favorites: '1M',
  ),
  Tweet(
    avatar: 'https://th.bing.com/th/id/R.8f2166f123b337dca5034e9199f39d11?rik=gbRMVXoxzLxNeg&pid=ImgRaw&r=0',
    username: 'Google Play',
    name: 'GooglePlay',
    timeAgo: '21m',
    text:
        'We’re exploring the world’s greatest stories through movies, TV, games, apps, books and so much more. Up for new adventures and discoveries? Let’s play.',
    comments: '1K',
    retweets: '70K',
    favorites: '2M',
  ),
  Tweet(
    avatar: 'https://th.bing.com/th/id/R.f5e4b831312744ffde47b9c33fcfd37f?rik=ilgELqqD%2fyydOg&pid=ImgRaw&r=0',
    username: 'Google',
    name: 'Google',
    timeAgo: '26m',
    text: 'HeyGoogle',
    comments: '10K',
    retweets: '500K',
    favorites: '22M',
  ),
  Tweet(
    // avatar: 'https://pbs.twimg.com/profile_images/1187814172307800064/MhnwJbxw_400x400.jpg',
    avatar:'https://www.best4geeks.com/wp-content/uploads/2018/08/48-lovely-cute-girl-picture-1024x816.jpg',
    username: 'Flutter',
    name: 'FlutterDev',
    timeAgo: '5m',
    text: 'Google’s UI toolkit to build apps for mobile, web, & desktop from a single codebase.',
    comments: '243',
    retweets: '23K',
    favorites: '112K',
  ),
  Tweet(
    avatar: 'https://writestylesonline.com/wp-content/uploads/2016/08/Follow-These-Steps-for-a-Flawless-Professional-Profile-Picture.jpg',
    username: 'Flutter en Español',
    name: 'EsFlutter',
    timeAgo: '12m',
    text: 'Comunidad Flutter de habla hispana!',
    comments: '46',
    retweets: '4K',
    favorites: '17K',
  ),
  Tweet(
    avatar: 'https://th.bing.com/th/id/R.bc9993d6b4ffc40622dcea75acf6c6dd?rik=w01gHU3pXz79Cg&riu=http%3a%2f%2f3.bp.blogspot.com%2f-Tfz6G_zsZkc%2fUhhnZ4aGwkI%2fAAAAAAAAEtk%2fHplbqw1xr_Y%2fs1600%2fa%2b(17).jpg&ehk=obAySeuTCDrB49SvrzOhcc%2bXxfIAxWqCd%2fwt196xX8k%3d&risl=&pid=ImgRaw&r=0',
    username: 'Android Dev',
    name: 'AndroidDev',
    timeAgo: '20m',
    text: 'News and announcements for developers from the Android team.',
    comments: '305',
    retweets: '20K',
    favorites: '1M',
  ),
  Tweet(
    avatar: 'https://th.bing.com/th/id/R.8f2166f123b337dca5034e9199f39d11?rik=gbRMVXoxzLxNeg&pid=ImgRaw&r=0',
    username: 'Google Play',
    name: 'GooglePlay',
    timeAgo: '21m',
    text:
        'We’re exploring the world’s greatest stories through movies, TV, games, apps, books and so much more. Up for new adventures and discoveries? Let’s play.',
    comments: '1K',
    retweets: '70K',
    favorites: '2M',
  ),
  Tweet(
    avatar: 'https://th.bing.com/th/id/R.f5e4b831312744ffde47b9c33fcfd37f?rik=ilgELqqD%2fyydOg&pid=ImgRaw&r=0',
    username: 'Google',
    name: 'Google',
    timeAgo: '26m',
    text: 'HeyGoogle',
    comments: '10K',
    retweets: '500K',
    favorites: '22M',
  ),
  Tweet(
    // avatar: 'https://pbs.twimg.com/profile_images/1187814172307800064/MhnwJbxw_400x400.jpg',
    avatar:'https://www.best4geeks.com/wp-content/uploads/2018/08/48-lovely-cute-girl-picture-1024x816.jpg',
    username: 'Flutter',
    name: 'FlutterDev',
    timeAgo: '5m',
    text: 'Google’s UI toolkit to build apps for mobile, web, & desktop from a single codebase.',
    comments: '243',
    retweets: '23K',
    favorites: '112K',
  ),
  Tweet(
    avatar: 'https://writestylesonline.com/wp-content/uploads/2016/08/Follow-These-Steps-for-a-Flawless-Professional-Profile-Picture.jpg',
    username: 'Flutter en Español',
    name: 'EsFlutter',
    timeAgo: '12m',
    text: 'Comunidad Flutter de habla hispana!',
    comments: '46',
    retweets: '4K',
    favorites: '17K',
  ),
  Tweet(
    avatar: 'https://th.bing.com/th/id/R.bc9993d6b4ffc40622dcea75acf6c6dd?rik=w01gHU3pXz79Cg&riu=http%3a%2f%2f3.bp.blogspot.com%2f-Tfz6G_zsZkc%2fUhhnZ4aGwkI%2fAAAAAAAAEtk%2fHplbqw1xr_Y%2fs1600%2fa%2b(17).jpg&ehk=obAySeuTCDrB49SvrzOhcc%2bXxfIAxWqCd%2fwt196xX8k%3d&risl=&pid=ImgRaw&r=0',
    username: 'Android Dev',
    name: 'AndroidDev',
    timeAgo: '20m',
    text: 'News and announcements for developers from the Android team.',
    comments: '305',
    retweets: '20K',
    favorites: '1M',
  ),
  Tweet(
    avatar: 'https://th.bing.com/th/id/R.8f2166f123b337dca5034e9199f39d11?rik=gbRMVXoxzLxNeg&pid=ImgRaw&r=0',
    username: 'Google Play',
    name: 'GooglePlay',
    timeAgo: '21m',
    text:
        'We’re exploring the world’s greatest stories through movies, TV, games, apps, books and so much more. Up for new adventures and discoveries? Let’s play.',
    comments: '1K',
    retweets: '70K',
    favorites: '2M',
  ),
  Tweet(
    avatar: 'https://th.bing.com/th/id/R.f5e4b831312744ffde47b9c33fcfd37f?rik=ilgELqqD%2fyydOg&pid=ImgRaw&r=0',
    username: 'Google',
    name: 'Google',
    timeAgo: '26m',
    text: 'HeyGoogle',
    comments: '10K',
    retweets: '500K',
    favorites: '22M',
  ),
];
